receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000

exporters:
  prometheusremotewrite:
    endpoint: "https://prometheus:9090/api/v1/write"
    tls:
      insecure: false
  loki:
    endpoint: "https://loki:3100/loki/api/v1/push"
    labels:
      resource:
        k8s.cluster.name: "$K8S_CLUSTER"
        k8s.namespace.name: "$K8S_NAMESPACE"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]